### ISSUE TITLE
Software para desenho no blog

### ISSUE THREAD

**Issue by mrcomoraes** [jhisse/jhisse.github.io#5]
@jhisse gostaria de saber qual software de desenho você usa em suas ilustrações. Li seu último post sobre tecnologias e decisões tomadas, mas não vi referência ao software de desenhos/diagramas. Poderia me passar o nome?

**Comment by jhisse** [comment]
Fala @mrcomoraes ! Desculpa a demora na resposta. Atualmente estou usando o [excalidraw](https://excalidraw.com). Gosto muito dele pela simplicidade e facilidade de fazer os diagramas e desenhos.

**Comment by mrcomoraes** [comment]
@jhisse muito obrigado pelo retorno.
